version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  liga-db:
    image: postgres:14-alpine
    container_name: liga-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=food_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liga"]
      interval: 10s
      timeout: 5s
      retries: 3

  liquibase:
    image: liquibase/liquibase:4.19.1
    container_name: liquibase
    depends_on:
      liga-db:
        condition: service_healthy
    command:
      - --url=jdbc:postgresql://liga-db:5432/food_service?user=postgres&password=postgres
      - --changeLogFile=master.xml
      - update
    volumes:
      - ./migration/src/main/resources/db/master.xml:/liquibase/master.xml
      - ./migration/src/main/resources/db/changelog:/liquibase/changelog

  delivery-service:
    build: ../delivery-service
    container_name: delivery-service
    ports:
      - "8050:8050"
    depends_on:
      kitchen-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/food_service
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - rabbit.host=rabbit

  kitchen-service:
    build: ../kitchen-service
    container_name: kitchen-service
    ports:
      - "8090:8090"
    depends_on:
      liquibase:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/food_service
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - delivery.service.url=http://delivery-service:8050
      - rabbit.host=rabbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  notification-service:
    build: ../notification-service
    container_name: notification-service
    ports:
      - "8060:8060"
    depends_on:
      kitchen-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/food_service
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  order-service:
    build: ../order-service
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://liga-db:5432/food_service
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - rabbit.host=rabbit

volumes:
  liquibase_data: