version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  liga-db:
    image: postgres:14-alpine
    container_name: liga-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=food_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  rabbitmq_data: